language: cpp
compiler:
  - clang

os:
  - linux
  - osx
  
script:
  - ./compile_clang.sh
  - (cd test && ./compile_clang.sh)
  - (cd src/examples && ./compile_clang.sh)
  - cd ./build
  - ASAN_OPTIONS=detect_stack_use_after_return=1 ./test
  - ASAN_OPTIONS=detect_stack_use_after_return=1 ./test_double
  - ASAN_OPTIONS=detect_stack_use_after_return=1 ./simple
  - sleep 1 # wait for output
